### PR TITLE
Validate Solpages 

### PR DESCRIPTION
**Pull request by Solpages**
# Validate [Solpages](https://solscan.io/token/BLXw8gGrwHeDMjEit5TN6VF9UqmYcesFhYejekSoX81d)

## Attestations (Please provide links):
- Tweet from your Twitter Account attesting the Mint address, tagging [@JupiterExchange](https://twitter.com/JupiterExchange) and showing community support: https://x.com/SolpagesToken/status/1797421022565781592
- Coingecko/ CMC URL (If available): https://www.coingecko.com/en/coins/YOUR_ID_HERE

## Validation (Please check off boxes):
- [X ] The metadata provided in the PR matches what is on-chain (Mandatory)
- [X ] Does not duplicate the symbol of another token on Jupiter's strict list (If not, review will be delayed)
- [ ] Is Listed on Coingecko / CMC (Optional, but helpful for reviewers) : CG has been applied for 

## Acknowledgement (Please check off boxes)
- [X ] My change matches the format in the file (no spaces between fields).
- [ X] My token is already live and trading on Jupiter.
- [X ] !!! I read the README section on Community-Driven Validation and understand this PR will be only be reviewed when there is community support on Twitter.
- [X ] Please make sure your pull request title has your token name. If it just says "Main", or "Validate", it will automatically be closed. PRs containing broken attestation or solscan links will also be closed.

### CODE REVIEW

**Comment by tdoxxed** [comment]
Solid project and team! all organic and working towards making a safer space!

**Comment by tdoxxed** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.
 Mint address: BLXw8gGrwHeDMjEit5TN6VF9UqmYcesFhYejekSoX81d
 Symbol: SOLP
 Token Decimals: 9
 Token icon: https://www.solpages.xyz/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FTitlePage2.1e75a2a3.png&w=1920&q=75
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by tdoxxed** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.
 Mint address: BLXw8gGrwHeDMjEit5TN6VF9UqmYcesFhYejekSoX81d
 Symbol: SOLP
 Token Decimals: 9
 Token icon: https://www.solpages.xyz/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FTitlePage2.1e75a2a3.png&w=1920&q=75
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by LekkerSolp** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.
 Mint address: BLXw8gGrwHeDMjEit5TN6VF9UqmYcesFhYejekSoX81d
 Symbol: SOLP
 Token Decimals: 9
 Token icon: https://www.solpages.xyz/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FTitlePage2.1e75a2a3.png&w=1920&q=75
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by ghost** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.
 Mint address: BLXw8gGrwHeDMjEit5TN6VF9UqmYcesFhYejekSoX81d
 Symbol: SOLP
 Token Decimals: 9
 Token icon: https://www.solpages.xyz/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FTitlePage2.1e75a2a3.png&w=1920&q=75
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by pidgeo0** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.
 Mint address: BLXw8gGrwHeDMjEit5TN6VF9UqmYcesFhYejekSoX81d
 Symbol: SOLP
 Token Decimals: 9
 Token icon: https://www.solpages.xyz/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FTitlePage2.1e75a2a3.png&w=1920&q=75
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by Simpolaya** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.
 Mint address: BLXw8gGrwHeDMjEit5TN6VF9UqmYcesFhYejekSoX81d
 Symbol: SOLP
 Token Decimals: 9
 Token icon: https://www.solpages.xyz/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FTitlePage2.1e75a2a3.png&w=1920&q=75
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Comment by Lljuipbd** [comment]
I can hereby attest that the provided information are accurate, and the token is valid.
 Mint address: BLXw8gGrwHeDMjEit5TN6VF9UqmYcesFhYejekSoX81d
 Symbol: SOLP
 Token Decimals: 9
 Token icon: https://www.solpages.xyz/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FTitlePage2.1e75a2a3.png&w=1920&q=75
 On-chain metadata matches
 No duplication on Jupiter's strict list

**Pull request merged**
